package advent2024

class Day08Test extends munit.FunSuite:
  val sample = """
    |T....#....
    |...T......
    |.T....#...
    |.........#
    |..#.......
    |..........
    |...#......
    |..........
    |....#.....
    |..........
    |""".stripMargin.trim

  test("count all interfering anti-nodes"):
    val actual = Day08.part1(Day08.testFile)
    assertEquals(actual, 14)

  test("count all harmonic anti-nodes in the sample"):
    val puzzle = new Day08.Puzzle(sample.linesIterator.map(IArray.from))
    val actual = puzzle.countAntiNodes(_.harmonic(_))
    assertEquals(actual, 9)

  test("count all harmonic anti-nodes in the file"):
    val actual = Day08.part2(Day08.testFile)
    assertEquals(actual, 34)
