package advent2024

class Day08Test extends munit.FunSuite:
  val sample = """
    |T....#....
    |...T......
    |.T....#...
    |.........#
    |..#.......
    |..........
    |...#......
    |..........
    |....#.....
    |..........
    |""".stripMargin

  test("count all interfering anti-nodes"):
    val actual = Day08.withTestFile(Day08.part1)
    assertEquals(actual, 14)

  test("count all harmonic anti-nodes in the sample"):
    val actual = Day08.withSample(sample)(Day08.part2)
    assertEquals(actual, 9)

  test("count all harmonic anti-nodes in the file"):
    val actual = Day08.withTestFile(Day08.part2)
    assertEquals(actual, 34)
